# Generated by Django 4.2.7 on 2023-12-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_categories_listings_comments_bids"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
