# Generated by Django 5.0 on 2024-03-22 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listings_category_remove_listings_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date',
            new_name='CreationDate',
        ),
        migrations.AddField(
            model_name='listing',
            name='endedDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
