# Generated by Django 5.0 on 2024-03-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_date_listing_creationdate_listing_endeddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='CreationDate',
            new_name='creationDate',
        ),
    ]
